// ESTA FUNÇÃO VAI ALTERAR PARA O DARK MODE.
// COM O DOCUMENT.BODY.CLASSLIST.TOGGLE IREMOS ALTERAR A TAG BODY ATRAVÉS DA CLASSE QUE DEFINIMOS COM O NOME "DARK". OU SEJA, QUANDO CLICARMOS NO BOTÃO, VAI MUDAR O STYLE DA TAG BODY.
function mudaTema() {
    document.body.classList.toggle("dark");
}
